wwade/jobrunner

job, jobrunner/db.py, jobrunner/test/integration/smoke_test.py
This will tail the log file instead of exiting after forking.
=> job: add '--monitor' option

job, jobrunner/db.py
From profiling, I noticed that most of the time in, e.g., job -L
was spent in opening and closing the db file.
Added in a read-only cached access mode for the DB, and also
refactored job.main options into NonExec and NonExecWrite versions,
where only the latter uses a read-write non-cached DB instance.
=> job: add db caching for some commands

job
When setting dependencies, there might be a lot of DB lookups, so it's best
to enable caching for all of the addDeps calls.
=> job: More top-level DB caching

jobrunner/info.py, jobrunner/test/info_test.py
Instead of the hand-rolled version, just rely on pipes.quote.  The
hand-rolled version wasn't quoting, for example, `!`, but pipes.quote
also takes care of this case.
Added a test case in info_test.py to verify the bang example.
=> info: use pipes.quote to generate cmdString

jobrunner/db.py, jobrunner/test/db_database_test.py
If the database read fails in some cases the database gets recreated
immediately.  It also happens if the schemaVersion changes.  It's not
super friendly, but at least make a copy of the old DB when this
happens.
=> db: make copy before trashing old DB

job, jobrunner/db.py, jobrunner/info.py, jobrunner/test/integration/smoke_test.py, jobrunner/utils.py
- Only show reminders with `-ll`
- Address integration test failures by skipping `runMeAsRoot`.
=> Skip reminders in active job list

jobrunner/config.py, jobrunner/db.py, jobrunner/test/config_test.py
Instead of displaying the full list of workspace + reminder text in the
watch mode (`job -W`), make it configurable in a new config `ui`
section.  The sumary mode just prints the reminder count, and the
invdividual reminders can be shown using `job -ll` or `job -a`.
=> watch: display only summary for reminders

.editorconfig
Use .editorconfig to set up the basic formatting config
across supported editors.
=> dev: Add .editorconfig

jobrunner/db.py, testenv
In case the db _has_ self.CHECKPOINT, but it returns an empty string,
also catch JSONDecodeError.
Fixed wrong var name in testenv as well.
=> db: safer checkpoint handling

job, jobrunner/db/__init__.py, jobrunner/db/dbm_db.py, jobrunner/db/sqlite_db.py, jobrunner/info.py, jobrunner/service/__init__.py, jobrunner/service/registry.py, jobrunner/test/db_database_test.py, jobrunner/test/db_sqlite_test.py, jobrunner/test/info_test.py, jobrunner/test/integration/integration_lib.py, jobrunner/test/integration/interrupt_running_test.py, jobrunner/test/integration/smoke_test.py, jobrunner/test/service_test.py, jobrunner/utils.py, requirements.testing.in, requirements.txt, testenv
- Major refactoring to use sqlite3 instead of dbm.  Also a lot of DB locking needed to be cleaned up.
- Use `pexpect` for more reliable integration tests, in some instances.
- Use a service API for the DB provider.
=> job: use sqlite3 instead of dbm

job, jobrunner/db/__init__.py, jobrunner/db/sqlite_db.py, jobrunner/info.py, jobrunner/service/registry.py, jobrunner/test/db_database_test.py, jobrunner/test/info_test.py, tox.ini
There doesn't seem to be any good reason for the "Not a valid entry"
sentinel values in the inactive DB for jobs that are still running.
This fixes a bug where `--prune` would crash while jobs are running.
=> db: Do not use sentinel value in inactive db

jobrunner/test/integration/integration_lib.py
For some reason, the Mojave job started having random errors while
cleaning up the DB state dir, (no such file in rmtree), so just
pass ignore_errors=True.
=> test: ignore rmtree errors

job, jobrunner/db/__init__.py, jobrunner/info.py, jobrunner/utils.py
This is a drop-in replacement for the `print` function, added because when jobs were
started and then the controlling terminal closed, they might error out at the end of
the job (if not running with --quiet, or if there was an error message to print out
from the message queue) with an IOError.
In the case of IOError from `print`, just discard it and continue.  For all other
exceptions, re-raise.
=>  safe-print: add exception-guarded `sprint` helper

job
Use <state-dir>/log/jobrunner-debug.log instead of /tmp/job.log
=> logging: Change --debug log file location

jobrunner/info.py, jobrunner/test/info_test.py, jobrunner/test/integration/integration_lib.py, jobrunner/test/integration/smoke_test.py
job -vvv Environment section shows all characters in hex encoding.  This was a result
of storing the job info in the database as unicode.
Added an intergration test case to the smoke test and updated existing unit tests. 
Fixes issue #42
=> info: Fix env printing

job, jobrunner/test/integration/smoke_test.py
Instead of requiring the user to hit CTRL-C, just
wait for the job to stop, and then exit.
=> job: monitor exit when finished

job, jobrunner/utils.py
Just makes it a bit nicer.  Also added a `lockedSection` helper instead of using
explicit lock/unlock calls in monitorForkedJob.
=> job: handle KeyboardInterrupt in monitor

jobrunner/info.py, jobrunner/test/info_test.py
For whatever reason, I had jobs with \xa0 characters in the command, and this was
causing a UnicodeDecodeError when listing / displaying job details.
Map all characters from 0x80 to 0xFF (inclusive) to "<80>" -> "<FF>" so that they
are displayed correctly.
=> info: escape non-ascii in info.cmdString

job, jobrunner/db/__init__.py, jobrunner/info.py
When retrying a job that has dependencies, print the 'retry job xxx' message first,
since that's the more important one.
After that, print dependency info, and finally, print the job key.  Also, indent the
dependency and key messages for some visual separation e.g.
```
retry job 'do something'
- adding dependency: 0:00:35 [15924762523803_sleep] sleep 100
- set key 15924762883805_do
```
=> ui: change output order for retry jobs

format.sh, tox.ini
For some reason it suddenly complains about some imaginary indent-size option in
pycodestyle, seemingly coming from autopep8. :shrugs:
=> env: make autopep8 happy with explicit --indent-size

Pipfile
This should hopefully cause dependabot to keep importlib-metadata around, for
example.
=> ci: add python_version 3.7 to Pipfile to match Pipfile.lock

jobrunner/plugins.py, setup.py
This will replace the old hacky plugins installed in jobrunner.plugin.
For now, just print a deprecation warning when using the old format.
Bump version to 2.1.0 since this is a significant change. 3.0.0 will remove suppoprt
for the old style plugins completely.
=> plugins: add support for entry_points wwade.jobrunner

Pipfile, Pipfile-2.7.lock, jobrunner/plugins.py, setup.py
lists of modules are not sortable, so just print out the deprecatedPlugins set as an
unsorted list instead.
=> plugins: add missing deps to setup.py and fix plugin loader

jobrunner/main.py, jobrunner/test/integration/interrupt_running_test.py, jobrunner/utils.py
--pid was not decoding the output from pstree, so it was printing out a byte-array
repr instead. Use the newly added autoDecode for the pstree output.
--int had some problems re-exec'ing python under sudo for virtualenv
installations. We can use sys.executable to ensure that we run the helper kill script
inside the same virtualenv (by reusing sys.executable) so that we're loading the
right jobrunner modules.
Updated the interrupt_running_test to check the --pid output, and also to ensure that
we can actually run the "sudo" test when sudo is available.
The problem causing failures in the integration test before was, presumably, that we
were too quick to kill the process with SIGTERM which means that it will not be able
to update the job db to remove the running job, and so the test thinks …
=> ui: fix '--pid' for python3 and improve '--int' wrt sudo

Pipfile, Pipfile-3.8.lock, ci/azure/azure-pipelines.yaml, jobrunner/compat.py, jobrunner/plugins.py
It's been moved to the standard library in 3.8+, so add a compatibility helper /
wrapper for the import.
=> general: support python >3.7 by guarding importlib_metadata import

jobrunner/main.py, jobrunner/test/main_test.py
After 45 characters, the isolate '-n' argument is generated from an md5 hash of the
command name. This requires a bytes-like object instead of a string for the
`.update()` calls.
=> main: fix isolate in py3 with long command names

Pipfile, Pipfile-2.7.lock, Pipfile-3.8.lock, Pipfile.lock, ci/azure/steps.yaml, setup.cfg, test.sh
Some IDEs like to use it by default, so add a compatible configuration.
=> ci: include flake8 in CI jobs

jobrunner/db/__init__.py, jobrunner/main.py, test.sh
When a job match isn't found, raise NoMatchingJobError and catch it in main instead
of letting a KeyError go all the way up uncaught.
=> main: print error message instead of throwing KeyError

jobrunner/test/utils_test.py, jobrunner/utils.py
Since we're probably going to be seeing either ASCII or UTF-8 input anyway, bump the
detection confidence requirement from 0.5 to 0.8. In the case of the first test input
shown in utils_test.py, it was coming in at 0.559 for Windows-1254 and just 0.505 for
UTF-8, when in fact, it's UTF-8.
This also makes me question using chardet at all, but it probably won't hurt at the
new confidence threshold.
=> utils: fix autoDecode error for specific sequence

jobrunner/db/__init__.py, jobrunner/main.py, jobrunner/test/integration/integration_lib.py, jobrunner/test/integration/smoke_test.py, pylintrc
Print nicer errors. See details in commits.
=> Fix errors related to empty database

jobrunner/plugins.py
If there's another plugin that provides it first, that would be used instead.
=> plugins: default workspaceIdentity to socket.gethostname

jobrunner/main.py
It's never a good idea to put error messages on stdout. Personally I often do things
like this:
tail -g `job -g foo`
And when there's no key for `foo` it's better to see the error instead of trying to
tail a bunch of nonsense file names based on the error output.
=> main: print key errors to stderr instead of stdout

jobrunner/db/__init__.py, jobrunner/main.py
- new feature `--list-keys`
- bug fix: KeyError output to `stderr` instead of `stdout`.
=> main: add --list-keys option to print only the job keys

jobrunner/compat.py, jobrunner/db/__init__.py, jobrunner/info.py, jobrunner/mail/chat.py, jobrunner/main.py, jobrunner/test/chatmail_test.py, jobrunner/test/integration/smoke_test.py, jobrunner/utils.py, test-docker.py, test.sh
pylint 2.10.2 adds some new warnings, so update the code to address those. Most
of the warnings were around the `encoding` argument for `open`. In another
instance it now notices using `split(..)[0]` without providing a `maxsplit`
argument of 1, which is a huge help!
=> lint: prepare for new pylint

README.rst, jobrunner/info.py, jobrunner/plugins.py, jobrunner/test/info_test.py, jobrunner/utils.py
It doesn't make sense to look for a magic environment variable WP, but we will
continue to do so if there's no plugin defined. Otherwise, return the value from the
plugin.
=> plugins: add plugin hook for workspaceProject

jobrunner/db/__init__.py, jobrunner/info.py, jobrunner/main.py, jobrunner/utils.py
The plugins' implementation of these methods could be somewhat expensive, so we don't
want to, for example, call workspaceProject() each time a JobInfo is initialized as
part of reading a job entry from the database.
To address this, we call resolve() to resolve the attributes' values in only two
instances:
1. when the job is created (but not yet started), and
2. when the job is started.
For the case of (2), `resolve(force=True)` is used so that we override the creation
values in case something has changed in the environment that might affect these values.
=> info: only resolve workspaceIdentity, workspaceProject as needed

jobrunner/db/sqlite_db.py, jobrunner/main.py, jobrunner/utils.py, pyproject.toml, setup.cfg
It's better to use a context manager for locks so that unlock calls are not missed.
Basically we just put a locked section around the implementation of "main", but back
out of it temporarily when we (maybe) fork the child process that runs the job. The
parent then exits (lock not held), while the child process will regain the lock while
it handles the rest of the options, finally releasing it before calling runJob.
In runJob, again, when it terminates, it updates the database and so uses another
lockedSection() call.
=> main: used lockedSection instead of explicit lock/unlock calls

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
=> Update codeql-analysis.yml to use v2

jobrunner/mail/chat.py, jobrunner/test/chatmail_test.py
The new pylint advises us that programs using requests.METHOD without a timeout can
hang forever, which seems surprising given that they're using TCP connections, but
even still, two hours is probably too long as well.
Added a timeout to "chatmail" with a default value of 10 seconds.
=> chat: add a timeout to requests.post call

ci/azure/azure-pipelines.yaml
Azure pipelines tells me that 10.15 is deprecated.
=> ci: move from macos-10.15 to macos-latest

jobrunner/main.py, jobrunner/utils.py
I ran a command that wrote a tarball into the job log file and so it
couldn't be decoded as utf-8. It subsequently caused autoDecode to
fail with a UnicodeDecodeError.
ValueError is an ancestor of UnicodeDecodeError and would hopefully
cover other decoding errors for other encodings as well.
=> mail: handle autoDecode failure for job logs with binary data

jobrunner/main.py
It's just a bit more convenient than typing "--retry" every time.
=> main: add "-y" alias for the "--retry" arg

ci/azure/azure-pipelines.yaml
It was previously not supported on azure, but now that it is, turn it on.
=> ci: include python3.10 in test matrix

jobrunner/plugins.py, jobrunner/test/plugin_test.py
The highest priority for a plugin is 0, the lowest is 1<<31. If there are multiple plugins providing a function at the same level, then it's down to the implementation in Plugins itself. Currently only getResources() combines the output from multiple plugins. workspaceIdentity() and workspaceProject() both return the response from the first plugin at a given level.
=> plugins: allow plugins to provide a relative priority value

jobrunner/db/__init__.py
Instead of dumping all the logs into a single directory, use an 8-bit hex-encoded prefix for each log file, e.g.
log/7a/somefile.log
log/33/otherfile.log
This avoids slowing down things like directory browsers, ls, etc.
=> db: change log directory format to use hash prefix

ci/azure/azure-pipelines.yaml
Ubuntu LTS 22.04 has been released, so test the newer python versions there. 20.04 comes with python 3.8, so just test with that version on 20.04.
For MacOS, the runner for MacOS 12 has been released, but keep testing 11 and python 3.8 for now.
=> ci: tweak CI matrix for OS versions

jobrunner/db/__init__.py, jobrunner/main.py
The default "limit=5" ended up applying to the "list inactive" call to getDbSorted() ever since 016cafdf57d7fb438b2b04bcea6033de97e10ded (version 2.6.0).
Explicitly pass in limit=None to avoid this problem and continue so show all of the inactive job entries.
=> ui: fix --list-inactive to show all inactive jobs

.github/workflows/codeql-analysis.yml, ci/azure/azure-pipelines.yaml, ci/azure/steps.yaml, test.sh
The Pipfile-(version).lock files were removed a while ago.
=> ci: we don't need to set up versioned lock files

.github/workflows/check.yml
Instead of having to add branch protection rules for each version in the test matrix, we can just "require" the "all-testing" job.
=> ci: add "all-testing" so that we can require that alone for 'main'

Pipfile, Pipfile.lock, jobrunner/test/integration/smoke_test.py
It will frequently hit a pexpect TIMEOUT in CI builds waiting for the notifier output, so let's just retry in that case.
Makes use of https://pypi.org/project/pytest-retry/.
Using the flaky mark causes only that test case to be retried.
=> test: mark RunExecOptionsTest.testWatchWait as flaky

jobrunner/info.py
The new pylint took exception with using `if` instead of the `max()` builtin, but then I discovered that max(list-comprehension) was twice as fast anyway.
=> job: improve "long line" calculation in JobInfo.showInOrder

jobrunner/db/__init__.py, jobrunner/test/utils_test.py, jobrunner/utils.py
- logging debug() takes an exc_info bool.
- chardet.detect() can return None, so handle that case.
=> utils: clean up pyright errors in utils.py
